"""deleted likes and dislike

Revision ID: 230ff2625edd
Revises: 62e8578b6df7
Create Date: 2023-08-29 19:11:56.992939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230ff2625edd'
down_revision = '62e8578b6df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_column('likes')
        batch_op.drop_column('dislikes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dislikes', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
