"""added description to threads, and removed title and description from comments

Revision ID: 62e8578b6df7
Revises: fdf4efb16830
Create Date: 2023-08-24 12:58:51.535858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e8578b6df7'
down_revision = 'fdf4efb16830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(), nullable=False))
        batch_op.drop_column('title')
        batch_op.drop_column('description')

    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
